# Generated by Django 2.0.1 on 2018-01-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='n_AC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='n_WA',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='n_submit',
            field=models.IntegerField(default=0),
        ),
    ]
