# Generated by Django 2.0.1 on 2018-01-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0002_auto_20180102_0657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sumit',
            new_name='Submit',
        ),
    ]
