# Generated by Django 2.0.1 on 2018-01-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0003_auto_20180102_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_ouput',
            field=models.TextField(blank=True),
        ),
    ]
