# Generated by Django 2.0.1 on 2018-01-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0004_auto_20180102_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='status',
            field=models.BooleanField(),
        ),
    ]
