# Generated by Django 2.0.1 on 2018-01-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0008_submit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='school',
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='臺灣科技大學', max_length=200),
            preserve_default=False,
        ),
    ]
