# Generated by Django 2.0.1 on 2018-01-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0009_auto_20180102_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
