# Generated by Django 2.0.1 on 2018-01-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0010_auto_20180102_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='code',
            field=models.TextField(default='no'),
            preserve_default=False,
        ),
    ]
