# Generated by Django 2.0.1 on 2018-01-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0011_submit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(blank=True),
        ),
    ]
